spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

openai:
  key: ${OPENAI_API_KEY}
  image-generation:
    endpoint: https://api.openai.com/v1/images/generations
    model: dall-e-3
    n: 1
    size: 1024x1024

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

ngrok:
  rest-docs:
    url: ${NGROK_URL}